/*
 * Copyright (c) 2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of the Metrological CBOR conformance tests
 * SPDX-License-Identifier: Apache-2.0
 */

//
// The certificate corpus this suite validates against, minted by Bouncy Castle.
//
// Why the certificates are generated by the C# side rather than written by the
// TypeScript one: COSE.TS reads X.509 with a DER parser of its own, and a
// parser tested against certificates its own writer produced tests nothing at
// all — the two would agree about any misreading equally. Certificates issued
// by an implementation that shares no code with it are the only ones whose
// agreement means something. That the corpus is also what the C# side reads
// back is the second half of the same argument.
//
// Everything here is deterministic on purpose: fixed private scalars, fixed
// serial numbers, fixed validity periods and a seeded random for the ECDSA
// nonces. Re-running the generator therefore produces the very same bytes, so
// a corpus in the repository can be regenerated and diffed rather than
// believed. Run it with:
//
//     dotnet run --project tools/CertificateCorpus
//
// The keys secure nothing. They are printed in the corpus.
//

using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

using Org.BouncyCastle.Asn1.X509;
using Org.BouncyCastle.Asn1.X9;
using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Crypto.Digests;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Crypto.Prng;
using Org.BouncyCastle.Math;
using Org.BouncyCastle.Crypto.Operators;
using Org.BouncyCastle.Security;
using Org.BouncyCastle.X509;

using org.GraphDefined.Vanaheimr.Illias;


// ------------------------------------------------------------------ setup ---

var repository  = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
var outputs     = new[] {
                      Path.Combine(repository, "vectors",  "cose-x509-corpus.json"),
                      Path.Combine(repository, "libs", "COSE.TS", "tests", "certificate-corpus.json")
                  };

// A seeded generator, so that the ECDSA nonces — and therefore every byte of
// every certificate — come out the same on every run.
var random = new SecureRandom(new DigestRandomGenerator(new Sha256Digest()));
random.SetSeed(Encoding.ASCII.GetBytes("Metrological CBOR conformance certificate corpus"));

var serialNumber   = 1000L;

var certificates   = new JsonObject();
var privateKeys    = new JsonObject();

DateTime At(String Iso)
    => DateTime.Parse(Iso, null, System.Globalization.DateTimeStyles.AdjustToUniversal |
                                 System.Globalization.DateTimeStyles.AssumeUniversal);

var authorityFrom  = At("2020-01-01T00:00:00Z");
var authorityUntil = At("2040-01-01T00:00:00Z");
var leafFrom       = At("2024-01-01T00:00:00Z");
var leafUntil      = At("2034-01-01T00:00:00Z");


// ------------------------------------------------------------------- keys ---

// Fixed scalars rather than generated ones. Any value below the group order
// is a private key; these are simply written out so that the corpus is the
// same on every machine.
AsymmetricCipherKeyPair EllipticCurveKey(String CurveName, String D)
{

    var parameters = ECNamedCurveTable.GetByName(CurveName)
                         ?? throw new Exception($"Unknown curve '{CurveName}'!");

    var oid        = ECNamedCurveTable.GetOid(CurveName)
                         ?? throw new Exception($"The curve '{CurveName}' has no object identifier!");

    // ECNamedDomainParameters rather than ECDomainParameters, and the
    // difference lands in the certificate: plain domain parameters make
    // Bouncy Castle write the curve out *explicitly* — p, a, b, G, n and h,
    // some 200 octets of it — where a named curve writes the object
    // identifier. RFC 5480 asks for the identifier, every real certificate
    // carries one, and a corpus written the other way would be testing a
    // shape nothing in the field produces.
    var domain     = new ECNamedDomainParameters(oid,
                                                 parameters.Curve,
                                                 parameters.G,
                                                 parameters.N,
                                                 parameters.H,
                                                 parameters.GetSeed());

    var privateKey = new ECPrivateKeyParameters(new BigInteger(D, 16), domain);

    return new AsymmetricCipherKeyPair(Crypto.CalculatePublicKey(privateKey), privateKey);

}

AsymmetricCipherKeyPair EdwardsKey(String Seed)
{
    var privateKey = new Ed25519PrivateKeyParameters(Convert.FromHexString(Seed), 0);
    return new AsymmetricCipherKeyPair(privateKey.GeneratePublicKey(), privateKey);
}

AsymmetricCipherKeyPair PostQuantumKey(String Seed)
{
    var privateKey = MLDsaPrivateKeyParameters.FromSeed(MLDsaParameters.ml_dsa_65,
                                                        Convert.FromHexString(Seed));
    return new AsymmetricCipherKeyPair(privateKey.GetPublicKey(), privateKey);
}


// ----------------------------------------------------------- the issuance ---

X509Certificate Issue(String                        Name,
                      String                        Subject,
                      AsymmetricCipherKeyPair       Subjects,
                      Boolean                       IsCertificateAuthority,
                      String                        SignatureAlgorithm,
                      (X509Certificate Certificate, AsymmetricKeyParameter Key)?  Issuer   = null,
                      DateTime?                     NotBefore    = null,
                      DateTime?                     NotAfter     = null,
                      Boolean                       AllowSigning = true)
{

    var generator = new X509V3CertificateGenerator();

    generator.SetSerialNumber(BigInteger.ValueOf(serialNumber++));
    generator.SetSubjectDN   (new X509Name($"CN={Subject}"));
    generator.SetIssuerDN    (Issuer.HasValue
                                  ? Issuer.Value.Certificate.SubjectDN
                                  : new X509Name($"CN={Subject}"));
    generator.SetNotBefore   (NotBefore ?? leafFrom);
    generator.SetNotAfter    (NotAfter  ?? leafUntil);
    generator.SetPublicKey   (Subjects.Public);

    generator.AddExtension(X509Extensions.BasicConstraints,
                           true,
                           new BasicConstraints(IsCertificateAuthority));

    generator.AddExtension(X509Extensions.KeyUsage,
                           true,
                           new KeyUsage(IsCertificateAuthority
                                            ? KeyUsage.KeyCertSign | KeyUsage.DigitalSignature
                                            : AllowSigning
                                                  ? KeyUsage.DigitalSignature
                                                  : KeyUsage.KeyEncipherment));

    var certificate = generator.Generate(
                          new Asn1SignatureFactory(SignatureAlgorithm,
                                                   Issuer.HasValue ? Issuer.Value.Key : Subjects.Private,
                                                   random)
                      );

    certificates[Name] = Convert.ToHexString(certificate.GetEncoded());

    return certificate;

}

void RecordKey(String Name, String Algorithm, String? Curve, String D)
{

    var entry = new JsonObject { ["algorithm"] = Algorithm };

    if (Curve is not null)
        entry["curve"] = Curve;

    entry["keyD"]      = D;
    privateKeys[Name]  = entry;

}


// ---------------------------------------------- the metrological hierarchy ---

// A root on P-256, a manufacturer authority on brainpoolP256r1 beneath it, and
// meters on brainpoolP256r1 beneath that: the shape a meter certificate
// actually arrives in, and a chain that changes curve halfway down — which is
// the case an implementation binding itself to one curve gets wrong.

const String rootD          = "3F0C488D0A2E3B6C5D4E1F9A8B7C6D5E4F3A2B1C0D9E8F7A6B5C4D3E2F1A0B9C";
const String manufacturerD  = "1A2B3C4D5E6F708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F809";
const String meterD         = "08F001BB03BEF4FBD1C59F10B50555CD37D2B53421331DBFA98815A581326FB3";
const String expiredD       = "2B3C4D5E6F708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F8091A";
const String futureD        = "3C4D5E6F708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F8091A2B";
const String encipherD      = "4D5E6F708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F8091A2B3C";
const String strangerD      = "5E6F708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F8091A2B3C4D";
const String underNonCaD    = "6F708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F8091A2B3C4D5E";
const String notACaD        = "708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F8091A2B3C4D5E6F";

var rootKey         = EllipticCurveKey("secp256r1",       rootD);
var manufacturerKey = EllipticCurveKey("brainpoolP256r1", manufacturerD);
var meterKey        = EllipticCurveKey("brainpoolP256r1", meterD);

var root            = Issue("metrologyRoot", "Metrology Root CA", rootKey, true,
                            "SHA256withECDSA", null, authorityFrom, authorityUntil);

var manufacturer    = Issue("manufacturerCA", "Meter Manufacturer CA", manufacturerKey, true,
                            "SHA256withECDSA", (root, rootKey.Private), authorityFrom, authorityUntil);

Issue("meter", "Meter 1ISA0000000042", meterKey, false,
      "SHA256withECDSA", (manufacturer, manufacturerKey.Private));

RecordKey("meter", "ESB256", "brainpoolP256r1", meterD);

Issue("expiredMeter", "Meter 1ISA0000000043", EllipticCurveKey("brainpoolP256r1", expiredD), false,
      "SHA256withECDSA", (manufacturer, manufacturerKey.Private),
      At("2020-06-01T00:00:00Z"), At("2021-06-01T00:00:00Z"));

RecordKey("expiredMeter", "ESB256", "brainpoolP256r1", expiredD);

Issue("notYetValidMeter", "Meter 1ISA0000000044", EllipticCurveKey("brainpoolP256r1", futureD), false,
      "SHA256withECDSA", (manufacturer, manufacturerKey.Private),
      At("2035-01-01T00:00:00Z"), At("2036-01-01T00:00:00Z"));

RecordKey("notYetValidMeter", "ESB256", "brainpoolP256r1", futureD);

Issue("encipherOnlyMeter", "Meter 1ISA0000000045", EllipticCurveKey("brainpoolP256r1", encipherD), false,
      "SHA256withECDSA", (manufacturer, manufacturerKey.Private), null, null, false);

RecordKey("encipherOnlyMeter", "ESB256", "brainpoolP256r1", encipherD);

// A perfectly good certificate for a key that did not sign anything: the
// chain validates and the binding does not.
Issue("strangerMeter", "Meter 1ISA0000000099", EllipticCurveKey("brainpoolP256r1", strangerD), false,
      "SHA256withECDSA", (manufacturer, manufacturerKey.Private));

RecordKey("strangerMeter", "ESB256", "brainpoolP256r1", strangerD);

// An issuer that is not a certification authority, and something beneath it.
var notACaKey = EllipticCurveKey("secp256r1", notACaD);
var notACa    = Issue("notACA", "Not A CA", notACaKey, false,
                      "SHA256withECDSA", (root, rootKey.Private), authorityFrom, authorityUntil);

Issue("meterUnderNonCA", "Meter 1ISA0000000046", EllipticCurveKey("brainpoolP256r1", underNonCaD), false,
      "SHA256withECDSA", (notACa, notACaKey.Private));

RecordKey("meterUnderNonCA", "ESB256", "brainpoolP256r1", underNonCaD);


// ------------------------------------------------------ the pure hierarchies ---

// Certificates *signed with* EdDSA and with ML-DSA, not merely certificates
// carrying such a key: the signature on the certificate is the thing being
// verified, so a chain signed with ECDSA proves nothing about the other two.

const String edwardsRootSeed  = "9D61B19DEFFD5A60BA844AF492EC2CC44449C5697B326919703BAC031CAE7F60";
const String edwardsMeterSeed = "4CCD089B28FF96DA9DB6C346EC114E0F5B8A319F35ABA624DA8CF6ED4FB8A6FB";

var edwardsRootKey  = EdwardsKey(edwardsRootSeed);
var edwardsMeterKey = EdwardsKey(edwardsMeterSeed);

var edwardsRoot     = Issue("edwardsRoot", "Edwards Root CA", edwardsRootKey, true,
                            "Ed25519", null, authorityFrom, authorityUntil);

Issue("edwardsMeter", "Meter Ed25519", edwardsMeterKey, false,
      "Ed25519", (edwardsRoot, edwardsRootKey.Private));

RecordKey("edwardsMeter", "Ed25519", "Ed25519", edwardsMeterSeed);

const String pqRootSeed  = "000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F";
const String pqMeterSeed = "202122232425262728292A2B2C2D2E2F303132333435363738393A3B3C3D3E3F";

var pqRootKey   = PostQuantumKey(pqRootSeed);
var pqMeterKey  = PostQuantumKey(pqMeterSeed);

var pqRoot      = Issue("pqRoot", "Post-Quantum Root CA", pqRootKey, true,
                        "ML-DSA-65", null, authorityFrom, authorityUntil);

Issue("pqMeter", "Meter ML-DSA-65", pqMeterKey, false,
      "ML-DSA-65", (pqRoot, pqRootKey.Private));

RecordKey("pqMeter", "ML-DSA-65", null, pqMeterSeed);


// ------------------------------------------------- a hierarchy nobody trusts ---

const String otherRootD  = "0A1B2C3D4E5F60718293A4B5C6D7E8F90A1B2C3D4E5F60718293A4B5C6D7E8F9";
const String otherInterD = "1B2C3D4E5F60718293A4B5C6D7E8F90A1B2C3D4E5F60718293A4B5C6D7E8F90A";

var otherRootKey  = EllipticCurveKey("secp256r1", otherRootD);
var otherRoot     = Issue("otherRoot", "Other Root CA", otherRootKey, true,
                          "SHA256withECDSA", null, authorityFrom, authorityUntil);

Issue("otherIntermediate", "Other Intermediate CA",
      EllipticCurveKey("secp256r1", otherInterD), true,
      "SHA256withECDSA", (otherRoot, otherRootKey.Private), authorityFrom, authorityUntil);


// ----------------------------------------------------------------- output ---

var corpus = new JsonObject {

    ["description"] = "X.509 certificates for the COSE cross-validation suite, minted by Bouncy Castle " +
                      "and read back by both implementations. Generated by tools/CertificateCorpus — " +
                      "deterministic, so regenerating it should change nothing. Every key here is printed " +
                      "in this file and secures nothing.",

    ["validateAt"]  = "2026-06-15T12:00:00Z",

    ["certificates"] = certificates,
    ["privateKeys"]  = privateKeys

};

var json = corpus.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine;

foreach (var path in outputs)
{
    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    File.WriteAllText(path, json);
    Console.WriteLine($"{certificates.Count} certificates, {privateKeys.Count} private keys -> {path}");
}
